DI-110 in master
eastgenomics/eggd_verifybamid pull request #6
Opened 2023-01-31 09:40 UTC by Emma-MacK

update verifybam id

2023-01-31 14:04 UTC, sophie22 requested changes
I added lots of comments, the majority of which is a larger scope of updates and best practice considerations, while a few are actually relevant minor correction suggestions.

> Reviewed 1 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-:-NN78-z7AjHovGulkvP1:b-6nh6h3)* status: all files reviewed, 16 unresolved discussions (waiting on @Emma-MacK and @mattgarner)

___
*[`dxapp.json` line 3 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN72xhuD5DFLMJRaNjt:-NN72xhuD5DFLMJRaNju:b-gotq5x) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L3)):*
> ```JSON
> {
>   "name": "eggd_verifybamid",
>   "version": "2.2.0",
> ```

might want to move the version after name, title and summary, just a preference
___
*[`dxapp.json` line 5 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73JngCbYYJCDL7lbX:-NN73Jnh0dQTerPFfHUn:b56p3ur) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L5)):*
> ```JSON
>   "version": "2.2.0",
>   "title": "verifyBamID",
>   "summary": "v2.2.0 - Detects sample contamination from genotypic profiles; forked from moka-guys v1.1.1",
> ```

I wonder if this is still relevant



_Code quote:_
```JSON
 forked from moka-guys v1.1.1"
```
___
*[`dxapp.json` line 6 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73NO59uW4UfMgVpLv:-NN73NO59uW4UfMgVpLw:bxrjqv) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L6)):*
> ```JSON
>   "title": "verifyBamID",
>   "summary": "v2.2.0 - Detects sample contamination from genotypic profiles; forked from moka-guys v1.1.1",
>   "tags": [
> ```

our other apps don't use tags. Could be a great time to start/look into their usefulness?
___
*[`dxapp.json` line 12 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73TyW5Fb4R4nFqXDu:-NN73TyW5Fb4R4nFqXDv:b-x0tqid) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L12)):*
> ```JSON
>   ],
>   "properties": {
>     "github release": "v2.2.0"
> ```

please remove, no longer relevant for APPs
___
*[`dxapp.json` line 42 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73Yyj3-3ki1iSxodV:-NN73Yyj3-3ki1iSxodW:bpnjsit) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L42)):*
> ```JSON
>     },
>     {
>       "name": "skip",
> ```

this is a workflow-related functional difference coming from moka-guys. I'm not aware of scenarios in our implementation where this is beneficial, but open to discuss
___
*[`dxapp.json` line 59 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73rSAE8O0UaVxGhcd:-NN73rSAE8O0UaVxGhce:b-m3pf3x) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L59)):*
> ```JSON
>     }
>   ],
>   "runSpec": {
> ```

I started ordering these as interpreter, release, version, file, timeoutPolicy as that is how it makes sense to me.
No functional difference either way
___
*[`README.md` line 3 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74E2w0OcsPYmj-5IZ:-NN74E2w0OcsPYmj-5I_:b32wx1) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L3)):*
> ```Markdown
> # eggd_verifybamid
> 
> eggd_ verifybamid is based on statgen/verifyBamID [v1.1.3] (tested with https://github.com/ewels/MultiQC/releases/tag/v1.3) made for use by the bioinformatics team at Addenbrookes for accessing contamination in genomic samples.
> ```

ss



_Code quote:_
```Markdown
cc
```
___
*[`README.md` line 8 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74K-PBpoO9NAzkIVm:-NN74K-PBpoO9NAzkIVn:b-ws5lsw) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L8)):*
> ```Markdown
> This app runs verifyBamID to detect sample contamination from population allele frequencies.
> 
> verifyBamID models the sequence reads as mixture of two unknown samples based on the allele frequency information in a provided VCF file. Markers are selected from the VCF where AF >= 0.010000 and callRate >= 0.500000, and contaminated sites are determined based on greater than expected heterozygousity rates.
> ```

where did you take these values from? are they planned to change in the future? is it beneficial to "hard-code" them in the readme?



_Code quote:_
```Markdown
AF >= 0.010000
```
___
*[`README.md` line 9 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74Y01EwGJbxoVGvKz:-NN74Y01EwGJbxoVGvL-:bxky9wz) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L9)):*
> ```Markdown
> 
> verifyBamID models the sequence reads as mixture of two unknown samples based on the allele frequency information in a provided VCF file. Markers are selected from the VCF where AF >= 0.010000 and callRate >= 0.500000, and contaminated sites are determined based on greater than expected heterozygousity rates.
> The VCF is packaged with the app under resources/home/dnanexus. # is this causing problems for me building the app?
> ```

shouldn't and you should not need to copy this VCF into your project for testing.
in a future update it might be good to have this as an input file rather than a fixed file bundled with the app. 



_Code quote:_
```Markdown
# is this causing
```
___
*[`README.md` line 17 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74xpX8ulVAY7jbFjS:-NN74xpX8ulVAY7jbFjT:bsb43fs) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L17)):*
> ```Markdown
> ## What data are required for this app to run?
> The app requires a BAM file (.bam) and a corresponding index file (.bai) to run.
> Additionally there is a skip argument requiring a Boolean True/False. If skip == True do not run the tool and no outputs are provided
> ```

I don't think it's relevant to our current implementation of this app.
___
*[`src/code.sh` line 2 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN75CXf3rdUnlK0d08H:-NN75CXf3rdUnlK0d08I:b-r8tj8n) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/b3086230d81176d4ab89d348c6fc35b6cd35d215/src/code.sh#L2)):*
> ```Shell
> #!/bin/bash
> # verifybamid_v2.1.0
> ```

I would keep this line and update the version
___
*[`src/code.sh` line 10 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN75hc6Aaq9Tk7JGHeG:-NN75hc6Aaq9Tk7JGHeH:bij4b7i) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L10)):*
> ```Shell
>      then
>      # Store the bam file name as a string
>      bam_file=`dx describe "${input_bam}" --name`
> ```

there's a dx built-in variable called $input_bam_prexif which is the filename string
https://documentation.dnanexus.com/developer/apps/advanced-app-tutorial#setting-input-files-using-bash-app-helper-variables
___
*[`src/code.sh` line 22 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN75Lxj8bNOfRran9xf:-NN75Lxj8bNOfRran9xg:b-xgzxx1) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L22)):*
> ```Shell
>      dx download "$input_bam_index" -o "${bam_prefix}.bai" 
>      dx download "$vcf_file" -o "$vcf_input"
>      
> ```

remove whitespace?
___
*[`src/code.sh` line 27 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN77DLU9RIKL5G7UEuR:-NN77DLU9RIKL5G7UEuS:bspgq9v) ([raw file](https://githu [...]

2023-01-31 17:03 UTC, mattgarner reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: all files reviewed, 16 unresolved discussions (waiting on @Emma-MacK and @sophie22)

___
*[`dxapp.json` line 3 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN72xhuD5DFLMJRaNjt:-NN7h63NBc5vFG7ed1MX:b-8ayu6x) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L3)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

might want to move the version after name, title and summary, just a preference
</blockquote></details>

Agree
___
*[`dxapp.json` line 5 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73JngCbYYJCDL7lbX:-NN7hHRn4obdqZFdx0Zg:bms7gel) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L5)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

I wonder if this is still relevant
</blockquote></details>

It's fine to keep these - we're giving credit to the original authors of the app
___
*[`dxapp.json` line 6 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73NO59uW4UfMgVpLv:-NN7hRBn2IUn97u-2nTB:b-jtmeu5) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L6)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

our other apps don't use tags. Could be a great time to start/look into their usefulness?
</blockquote></details>

Adding the tags is a good idea, but I'm going to ask that they be removed until we have a process for their addition, define their purpose, and standardise the tags used across all apps. 
___
*[`dxapp.json` line 12 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73TyW5Fb4R4nFqXDu:-NN7hz0M9vuiPrYc0dld:b-3fbtgc) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L12)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

please remove, no longer relevant for APPs
</blockquote></details>

To be clear, the github release field can be removed. Since that is the only field in properties, that too can be removed since it will then be empty
___
*[`src/code.sh` line 10 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN75hc6Aaq9Tk7JGHeG:-NN7jYus9_4O3uRfEuNK:br0r3r3) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L10)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

there's a dx built-in variable called $input_bam_prexif which is the filename string
https://documentation.dnanexus.com/developer/apps/advanced-app-tutorial#setting-input-files-using-bash-app-helper-variables
</blockquote></details>

Good idea. Note that there's a typo in the comment above - it should be `$input_bam_prefix`

You can also get input file names using the helper variables with the `_name` suffix, so in this case the $input_bam_name variable can be used instead of:
bam_file=`dx describe "${input_bam}" --name`
to get the bam filename
___
*[`src/code.sh` line 27 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN77DLU9RIKL5G7UEuR:-NN7lRD-DgYGqMIvscqQ:bex7355) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L27)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

our implementation of the app makes no use of the QC subfolder, so it may be removed (keeping in my downstream effect, but I can only think of MultiQC where input file location are controlled in the config anyway)
</blockquote></details>

Agree that it's not required, but let's keep that output folder for consistency with past versions of the app
___
*[`src/code.sh` line 33 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN77dZm3U_TFEw8KQ9t:-NN7lg5X0u9GZsJ1tNxm:b-3pcq0i) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L33)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

the tool itself is bundled with the app, which is not in line with current practice for other apps. Could/should this be made an input instead?
</blockquote></details>

This is a fair point, but this case is somewhat unusual in that there will never be a new release of verifybamid, so no need to be able to pass a new one as input. Keep as it is please, but know that what Sophie has suggested is usually a good idea


<!-- Sent from Reviewable.io -->

2023-02-01 09:59 UTC, Emma-MacK reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: 2 of 3 files reviewed, 13 unresolved discussions (waiting on @sophie22)

___
*[`dxapp.json` line 3 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN72xhuD5DFLMJRaNjt:-NNBNeJJ5ZWSMMuKBq-o:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L3)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Done.
___
*[`dxapp.json` line 6 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73NO59uW4UfMgVpLv:-NNBNlBr2mDD8IWJG2JN:bowjfiu) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L6)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Adding the tags is a good idea, but I'm going to ask that they be removed until we have a process for their addition, define their purpose, and standardise the tags used across all apps. 
</blockquote></details>

Done. Tags have been removed
___
*[`dxapp.json` line 12 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73TyW5Fb4R4nFqXDu:-NNBNr_j8Sz6_F0EchkA:b-g76sjx) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L12)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

To be clear, the github release field can be removed. Since that is the only field in properties, that too can be removed since it will then be empty
</blockquote></details>

Done. Properties segment has been removed
___
*[`dxapp.json` line 42 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73Yyj3-3ki1iSxodV:-NNBO1R-A15B5ZmFNSE5:b6jy1ak) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L42)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

this is a workflow-related functional difference coming from moka-guys. I'm not aware of scenarios in our implementation where this is beneficial, but open to discuss
</blockquote></details>

I can remove the skip argument if I remove it in code.sh as well. Having it means during development it can check if the DNAnexus will run the tool at all in a short period of time. But it is easy to remove if it is not wanted.
___
*[`dxapp.json` line 59 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73rSAE8O0UaVxGhcd:-NNBP4hH8TMp5Zcantp4:b79xhhg) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L59)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

I started ordering these as interpreter, release, version, file, timeoutPolicy as that is how it makes sense to me.
No functional difference either way
</blockquote></details>

Done. I have reordered the code.


<!-- Sent from Reviewable.io -->

2023-02-01 11:13 UTC, sophie22 requested changes
Thanks for making the changes to dxapp.json, please add back the release and interpreter fields within the runSpec section.

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-:-NNBfPFi9AonC-Xi-cFZ:bqh9tr9)* status: all files reviewed, 10 unresolved discussions (waiting on @Emma-MacK)

___
*[`dxapp.json` line 59 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73rSAE8O0UaVxGhcd:-NNBexLf5YFs2KNJZQDV:b-nj0igc) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L59)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

Done. I have reordered the code.
</blockquote></details>

sorry, my comment may not have been clear. You still need to have the release and interpreter. That's what specifies the worker instance and interpreter for running the app scripts. Please add back 'release' and 'interpreter'.


<!-- Sent from Reviewable.io -->

2023-02-01 13:23 UTC, Emma-MacK reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: 2 of 3 files reviewed, 10 unresolved discussions (waiting on @sophie22)

___
*[`dxapp.json` line 59 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73rSAE8O0UaVxGhcd:-NNC4BQt1hw7Xf-i7IkL:b-8msj5t) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L59)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

sorry, my comment may not have been clear. You still need to have the release and interpreter. That's what specifies the worker instance and interpreter for running the app scripts. Please add back 'release' and 'interpreter'.
</blockquote></details>

As far as I can tell they are still there on the latest commit, just moved to the top of the runSpec segment
___
*[`README.md` line 3 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74E2w0OcsPYmj-5IZ:-NNC5-Rq35nkK6Ps8w8R:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L3)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

ss
</blockquote></details>

Done.
___
*[`README.md` line 8 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74K-PBpoO9NAzkIVm:-NNC59WADnXLkFg1PwH0:b-v9p26u) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L8)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

where did you take these values from? are they planned to change in the future? is it beneficial to "hard-code" them in the readme?
</blockquote></details>

These are the values included by the moka-guys in their description of the app, but I can remove it if you would prefer 
___
*[`README.md` line 9 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74Y01EwGJbxoVGvKz:-NNC5KZOEgPRPQxlShDN:b-ehvmcc) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L9)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

shouldn't and you should not need to copy this VCF into your project for testing.
in a future update it might be good to have this as an input file rather than a fixed file bundled with the app. 
</blockquote></details>

Done. The previous eggd version did require a vcf as an input, and had removed the "download VCF" section from code.sh. This was where the eggd version differed from the moka-guys version, and when I updated code.sh to reflect the moka-guys version the handling of the VCF was causing issues, so I reverted vcf handling to that of the previous eggd version. I have updated the README to reflect this change and removed the comment
___
*[`README.md` line 17 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74xpX8ulVAY7jbFjS:-NNC7H_g4wGfuMlHwOKY:bf213uq) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L17)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

I don't think it's relevant to our current implementation of this app.
</blockquote></details>

Potentially not but I will include unless we decide to remove the skip argument from the JSON and code.sh files 


<!-- Sent from Reviewable.io -->

2023-02-01 16:06 UTC, Emma-MacK reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: 2 of 3 files reviewed, 10 unresolved discussions (waiting on @sophie22)

___
*[`src/code.sh` line 2 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN75CXf3rdUnlK0d08H:-NNCfxrH--LSHxPrEeln:b-b32yrm) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/b3086230d81176d4ab89d348c6fc35b6cd35d215/src/code.sh#L2)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

I would keep this line and update the version
</blockquote></details>

can you clarify what you mean by version here? as in the version in the JSON
___
*[`src/code.sh` line 10 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN75hc6Aaq9Tk7JGHeG:-NNCheCW06O2IZyLPREK:b-52e40v) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L10)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Good idea. Note that there's a typo in the comment above - it should be `$input_bam_prefix`

You can also get input file names using the helper variables with the `_name` suffix, so in this case the $input_bam_name variable can be used instead of:
bam_file=`dx describe "${input_bam}" --name`
to get the bam filename
</blockquote></details>

This will take some time to change so I can fully understand the differences between the variables. But I will make that change
___
*[`src/code.sh` line 22 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN75Lxj8bNOfRran9xf:-NNCiAuXDM0dh93rwsSt:b-kzwnz2) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L22)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

remove whitespace?
</blockquote></details>

Done. removed unnecessary comments, I've kept some white space as I feel it makes it more readable 
___
*[`src/code.sh` line 27 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN77DLU9RIKL5G7UEuR:-NNCiPaG4FilGDpwsjih:b2cx333) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L27)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Agree that it's not required, but let's keep that output folder for consistency with past versions of the app
</blockquote></details>

updated to remove QC subfolder 
___
*[`src/code.sh` line 45 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN77poz0zxLVzbS6AvO:-NNCiZh6Ek3OucshapHy:bs7wumx) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/b3086230d81176d4ab89d348c6fc35b6cd35d215/src/code.sh#L45)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

is the correct one, since it's the name of the cloud-computing platform
</blockquote></details>

Done. 


<!-- Sent from Reviewable.io -->

2023-02-02 11:35 UTC, Emma-MacK commented
I have made the suggested changes, and have updated code.sh to use the helper variables, which runs as expected. I will perform the in depth tests of this version of the app unless there are more suggestions

2023-02-02 18:55 UTC, sophie22 requested changes
> Reviewed 1 of 1 files at r7, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: all files reviewed, 6 unresolved discussions (waiting on @Emma-MacK)

___
*[`dxapp.json` line 59 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73rSAE8O0UaVxGhcd:-NNITnGK8l_wvQWbvRds:b-nx6tz) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L59)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

As far as I can tell they are still there on the latest commit, just moved to the top of the runSpec segment
</blockquote></details>

You are right, I only focused on having seen these lines in red in Reviewable and panicked that they got removed.
___
*[`src/code.sh` line 22 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN75Lxj8bNOfRran9xf:-NNGzA7I3HNGqa4ZkKFU:bgt15pm) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L22)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

Done. removed unnecessary comments, I've kept some white space as I feel it makes it more readable 
</blockquote></details>

you can have a new line for spacing but remove the whitespace characters (these show up as dots here)
___
*[`src/code.sh` line 27 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN77DLU9RIKL5G7UEuR:-NNGz_4x5zPK8z6HqRvN:b-ywsqxy) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L27)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

updated to remove QC subfolder 
</blockquote></details>

apologies for the contradicting instructions, Matt has the final say which is to keep the QC folder for now.
it would require additional testing not just of the app but downstream as well.


<!-- Sent from Reviewable.io -->

2023-02-07 07:57 UTC, mattgarner requested changes
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: all files reviewed, 8 unresolved discussions (waiting on @Emma-MacK and @sophie22)

___
*[`src/code.sh` line 9 at r10](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NNeqkZPAznUpyaWdvCe:-NNeqkZQ4BwDZuwdLIt1:b45hpez) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c30837b57da2f126a330c79b12e4cb04a87fdb2f/src/code.sh#L9)):*
> ```Shell
> if [ $skip == false ];
>      then
>      
> ```

Unnecessary whitespace. Please remove the extra spaces in this line



_Code quote:_
```Shell
·····
```
___
*[`src/code.sh` line 18 at r10](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NNeqziv8HE93iNEeS3z:-NNeqziv8HE93iNEeS4-:bdzzdcy) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c30837b57da2f126a330c79b12e4cb04a87fdb2f/src/code.sh#L18)):*
> ```Shell
>      # store vcf file name as a string
>      vcf_input=`dx describe "${vcf_file}" --name`
>      
> ```

Whitespace



_Code quote:_
```Shell
·····
```


<!-- Sent from Reviewable.io -->

2023-02-07 08:29 UTC, sophie22 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: all files reviewed, 8 unresolved discussions (waiting on @Emma-MacK)

___
*[`dxapp.json` line 59 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73rSAE8O0UaVxGhcd:-NNeyrEh699-LxZ9wMLE:bsn8sj9) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L59)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

You are right, I only focused on having seen these lines in red in Reviewable and panicked that they got removed.
</blockquote></details>

I missed out ‘distribution’ which should come after ‘interpreter’ and before ‘release’.


<!-- Sent from Reviewable.io -->

2023-02-08 08:45 UTC, mattgarner reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: all files reviewed, 8 unresolved discussions (waiting on @Emma-MacK and @sophie22)

___
*[`dxapp.json` line 42 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73Yyj3-3ki1iSxodV:-NNgd25E1W9qDd3vhbl3:b5riep2) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L42)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

I can remove the skip argument if I remove it in code.sh as well. Having it means during development it can check if the DNAnexus will run the tool at all in a short period of time. But it is easy to remove if it is not wanted.
</blockquote></details>

I agree with Sophie - the skip functionality is not required and can be removed.
___
*[`README.md` line 17 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74xpX8ulVAY7jbFjS:-NNgdG8xDeCot99npRnQ:b-1ayymy) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L17)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

Potentially not but I will include unless we decide to remove the skip argument from the JSON and code.sh files 
</blockquote></details>

This can be dropped along with skip
___
*[`src/code.sh` line 27 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN77DLU9RIKL5G7UEuR:-NNggs4ZDs1ISV2kZLWV:b4shyiz) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L27)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

apologies for the contradicting instructions, Matt has the final say which is to keep the QC folder for now.
it would require additional testing not just of the app but downstream as well.
</blockquote></details>

Sophie has convinced me that I am wrong :)

The correct decision is to remove the QC folder, so no further changes required for this 


<!-- Sent from Reviewable.io -->

2023-02-09 09:38 UTC, Emma-MacK reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[`dxapp.json` line 42 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN73Yyj3-3ki1iSxodV:-NNpTutYDIEKpzsEdoRM:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/dxapp.json#L42)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

I agree with Sophie - the skip functionality is not required and can be removed.
</blockquote></details>

Done.
___
*[`README.md` line 17 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN74xpX8ulVAY7jbFjS:-NNpU_zd6-yWEyIYipo9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/README.md#L17)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

This can be dropped along with skip
</blockquote></details>

Done.
___
*[`src/code.sh` line 22 at r5](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NN75Lxj8bNOfRran9xf:-NNpXW-W22pmCWMYQugt:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/9937a1214f897952bbad64b5a8efb2605b8631fc/src/code.sh#L22)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

you can have a new line for spacing but remove the whitespace characters (these show up as dots here)
</blockquote></details>

Done.
___
*[`src/code.sh` line 9 at r10](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NNeqkZPAznUpyaWdvCe:-NNpWhdtDgD-dvs-3t3d:bvl12k1) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c30837b57da2f126a330c79b12e4cb04a87fdb2f/src/code.sh#L9)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Unnecessary whitespace. Please remove the extra spaces in this line
</blockquote></details>

Done. removed by removing skip argument 
___
*[`src/code.sh` line 18 at r10](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NNeqziv8HE93iNEeS3z:-NNpWvOmDvXAcvl__tAk:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/c30837b57da2f126a330c79b12e4cb04a87fdb2f/src/code.sh#L18)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Whitespace
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-09 14:49 UTC, mattgarner approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: all files reviewed, 6 unresolved discussions (waiting on @sophie22)



<!-- Sent from Reviewable.io -->

2023-02-09 15:17 UTC, sophie22 requested changes
1 more tiny suggestion, please see comment

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-:-NNqk2sF1wwGM07qaynH:b9fi071)* status: all files reviewed, 1 unresolved discussion (waiting on @Emma-MacK)

___
*[`src/code.sh` line 11 at r11](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NNqjkzL5PNPN9KcaDzf:-NNqjkzMDqsi9FAmvc4v:b-cmst8d) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/4670d12368256b777b3b7edac3668124d02dad1a/src/code.sh#L11)):*
> ```Shell
> dx download "$input_bam" -o "$input_bam_name"
> dx download "$input_bam_index" -o "${input_bam_prefix}.bai"
> dx download "$vcf_file" -o "$vcf_input"
> ```

you could use the built-in vcf_input_name variable here as well, to directly download the file from DNAnexus with it's filename



_Code quote:_
```Shell
vcf_input
```


<!-- Sent from Reviewable.io -->

2023-02-09 16:05 UTC, Emma-MacK reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @sophie22)

___
*[`src/code.sh` line 11 at r11](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NNqjkzL5PNPN9KcaDzf:-NNqv4ed6PoYokIyo1at:b-x5q1px) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/4670d12368256b777b3b7edac3668124d02dad1a/src/code.sh#L11)):*
<details><summary><i>Previously, sophie22 (Sophie Ratkai) wrote…</i></summary><blockquote>

you could use the built-in vcf_input_name variable here as well, to directly download the file from DNAnexus with it's filename
</blockquote></details>

Done. Just testing now


<!-- Sent from Reviewable.io -->

2023-02-09 16:40 UTC, sophie22 requested changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: all files reviewed, 1 unresolved discussion (waiting on @Emma-MacK)

___
*[`src/code.sh` line 11 at r11](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6#-NNqjkzL5PNPN9KcaDzf:-NNr1uCq9n4EDluWbp3l:bc6sct9) ([raw file](https://github.com/eastgenomics/eggd_verifybamid/blob/4670d12368256b777b3b7edac3668124d02dad1a/src/code.sh#L11)):*
<details><summary><i>Previously, Emma-MacK wrote…</i></summary><blockquote>

Done. Just testing now
</blockquote></details>

it's probably $vcf_file_name



_Code quote:_
```Shell
vcf_file
```


<!-- Sent from Reviewable.io -->

2023-02-09 16:45 UTC, sophie22 approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_verifybamid/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Emma-MacK)



<!-- Sent from Reviewable.io -->

2023-02-10 11:49 UTC, merged